security:
  oauth2:
    client:
      grant-type: client_credentials
      clientId: myclient
      clientSecret: mysecret
      access-token-uri: http://localhost:8080/oauth/token
    resource:
      userInfoUri: http://localhost:8080/validateUser
server:
  port: 9090